 spring:
   h2.console:
        enabled: true
        path: '/console'
   jpa.hibernate:
        ddl-auto: create-drop
   datasource:
     url: 'jdbc:h2:file:./todo-db'
 task.template.allowMultipleTasks: false